### ISSUE TITLE
Helm or Leg enchants de-activating upon death

### ISSUE THREAD

**Issue by Ifixstuffk** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#122]
For some reason, they are not calculated anymore after your first death post-enchant.

Not sure if it's legs or head.

**Comment by Yiemeh** [comment]
Nah, the actual bug is you get an "extra" enchant upon login, which is removed once you die. At least this was the case on old feenix 1.12. Can be abused and should be fixed.

Affected enchants are all head/legs enchants and shoulder enchants from sapphiron (ZG shoulder enchs are not affected by this bug)

**Comment by Ifixstuffk** [comment]
Alright, either way it should be fixed.

**Comment by devidao** [comment]
it is fixed on https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/122
