### ISSUE TITLE
Holy Shield Causing Multiple Kills, Can't Loot Mob

### ISSUE THREAD

**Issue by Killergoose** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#1503]
When I use Holy Shield (rank 3, if it matters, although I haven't experimented with rank 1 and 2),  if the opponent dies to this, it will die twice, and in combat log shows it as such. With this however, the enemy will not drop any loot, and will quickly despawn. This is a major problem, especially with bosses and mobs.

It also has been shown to die three times in a row, with the same thing with it not dropping any loot and will despawn quick. This seems to occur if Redoubt is on. or possibly if Holy Shield and Blessing of Sanctuary both proc and kill it.

**Comment by redmagejoe** [comment]
Any confirmation that this fix is applied to ALL SOURCES of damage return? Was the fix to a core behavior of damage return, or specifically to the code of Holy Shield?

**Comment by Salce** [comment]
Fix applied on live.

**Comment by redmagejoe** [comment]
Anyone?

**Comment by Nzzoth** [comment]
Anyone what Redmagejoe?

**Comment by redmagejoe** [comment]
Is this fix only for Holy Shield or all dmg return sources?

**Comment by Nzzoth** [comment]
Are there problems with other spells with damage return?

**Comment by redmagejoe** [comment]
As I have mentioned through the course of the bug report (see my previous posts, not sure how to cite) It has been found and become common knowledge on the server that all forms of damage return have this behavior, not just Holy Shield.

I and other players have personally tested and found that shield spikes, Thorns, Ret Aura, Holy Shield, Naglering, Blessing of Sanctuary,  all have killed mobs and resulted in multi-deaths, multiplying experience and rendering the mobs unlootable. Thus I asked if the fix was a fix to core combat or to the spell itself. If the latter, dmg return is still going to create serious problems, namely players exploiting for fast experience, while honest players risk losing loot from the endboss of a dungeon.

Going through BRD and having Emperor die to shield spike is VEXING and renders the enchant nonviable and unwanted. Classes are asked not to use their skills for fear of ruining runs.

**Comment by redmagejoe** [comment]
A new bug related tentatively to this has surfaced, so I will make a new bug report with video footage. Testing has revealed the following, which I have video footage to prove:

Naglering no longer causes multikills.
Thorns no longer causes multikills.
Retribution Aura no longer causes multikills.
Cannot properly test Shield Spikes due to NEW bug.
Cannot properly test Holy Shield due to NEW bug.
Cannot properly test Blessing of Sanctuary due to NEW bug.

I will open a new report and reference this issue detailing the new bug that seems more related to blocking with a shield than with the spells themselves, as all the affected spells deal with blocking with a shield. Testing, in spite of the NEW bug, SEEMED to indicate that Holy Shield, Blessing of Sanctuary, and Shield Spikes no longer cause multikills. As a result I will tentatively say that this bug report should remain closed and the issue resolved, the issue being not only Holy Shield, but all forms of damage return causing multikills and thus unlootable mobs.

**Comment by redmagejoe** [comment]
This bug needs to be reopened, as of last patch it has RETURNED, and we have been losing loot on bosses with a Paladin tank.

**Comment by Xalpen** [comment]
Also happens with thorium shield spike.
