### ISSUE TITLE
Delete. Seem to be working fine

### ISSUE THREAD

**Issue by Bigepo** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#28]
Seem to be working fine after some testing.

**Comment by Zerixx** [comment]
What spells do it right, what spells don't? Can you clear this up? Any more information you can give us will be all the more helpful!

Thanks for the report, nonetheless. We appreciate it!

**Comment by Bigepo** [comment]
Hi again.
I havent botherd to check the amounts on this server.. but if u get hit by 1000dmg from melee, u get like 40rage... but if u get hit by 1000 spell. u get 7rage.....
wich make warriors utter crap vs casters..

You should get same rage from damage taken, melee or spells :)

I can show this in video. will upload later :)

**Comment by Yiemeh** [comment]
Rage from magic taken should be same as physical yeah, at 90 damage for 1 rage from a lvl 60 enemy.

**Comment by Cabro** [comment]
Please upload a video :)

**Comment by Yiemeh** [comment]
You meant me Cabro? I've been meaning to make a report regarding rage mechanics on feenix, there are several issues. I'm too lazy atm

**Comment by Cabro** [comment]
Can this get a bump in the priority for bugs? Never got fixed on old Warsong, would liek to see it fixed before Warsong 3.0

**Comment by Yiemeh** [comment]
https://youtu.be/2FdH5R7q6tY?t=50

Set it to 0.5 speed and check 0:55. He takes 899 damage and gets 9 rage (90 damage for 1 rage is not the exact formula but a close estimation). So warriors getting like 40 rage from 1000 incoming damage is way off. Also note that raggy should actually hit with physical damage on his auto attacks but that's a subject for another report.

**Comment by Nzzoth** [comment]
Funny Bigepo, I just received confirmation from a Developer that rage generation from spells in fact does work fine. Thing is that means something is wrong with physical damage. :)

**Comment by Bigepo** [comment]
I don't know. We just tested from spells. Wich was more or less correct.

**Comment by ivid** [comment]
Hello,
I've looked into this issue and rage generation is as expected for both spell and physical damage (at mentioned ~90 damage per 1 rage).

As @Cabro had asked on old issue tracker: "Why this discrepancy?" (meaning between spell and physical damage rage gains).
Answer is that rage is generated (as it should be) before reductions are taken into account.
So a hit on t3 warrior that ends up as ~140 damage and generates roughly 3 rage is because this damage was ~330 before armor reductions.
While same does apply to spells, it's not as obvious because players often have very little spell resistances compared to armor.
