### ISSUE TITLE
[Quest] Arcane Feedback

### ISSUE THREAD

**Issue by Eonall** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4783]
I do not believe the quest text is correct for Brother Joshua.

http://postimg.org/image/xpn7c8ceh/

I feel that this quest text belongs to a priest trainer of Darnassus who refers you to Stormwind, while the text from 
http://db.vanillagaming.org/?quest=5677#wh-comments
refers you from Ironforge to Stormwind. Unfortunately I cannot find a source to show which Darnassus trainer should give the quest.

I'm doubtful Brother Joshua should be included at all, and if you are in stormwind you should simply start the quest http://www.wowwiki.com/Quest:Arcane_Feedback straight from Laurena.

The quest text clearly implies being of a different race, although my character and the NPC are both human. Brother Joshua also references "returning to the cathedral" although he is actually already located in it.

Perhaps someone else can shed some light on where to find the correct quest details?

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by Nzzoth** [comment]
**Fix denied on PTR**

**Comment by devidao** [comment]
I think before Goran fix that all was fine, look at http://www.wow-one.com/database/index.php?quest=5676 and http://www.wow-one.com/database/index.php?quest=5677 all looks correct (text and questgivers). 

I reverted last fix.

**Comment by devastator** [comment]
No it was not.. http://www.wow-one.com/database/index.php?quest=5676 is offered wrongly by NPC in Stormwind and it redirects you to.. Stormwind. I doubt it the fix was properly applied to PTR at all or noone actually knows whats the issue but me...
What the fix does:
Quest http://www.wow-one.com/database/index.php?quest=5676 is offered now by http://www.wowhead.com/npc=11406/high-priest-rohan in Ironforge and
quest http://www.wow-one.com/database/index.php?quest=5677 is offered by http://www.wow-one.com/database/index.php?npc=11401 in Darnassus
Please reapply and retest, thank you

**Comment by devidao** [comment]
re-fixed

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**
