### ISSUE TITLE
[Naxxramas] Ke'thuzad's Shaddow Fissure shouldn't be positioned under players in Frost Blast.

### ISSUE THREAD

**Issue by Cabro** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5124]
This is... i dont even know where to start.
Never saw this happening on retail, neither on the vanilla version nor in the wotlk version.

There should be a check to see if the player that is the target for the shadow fissure is already in Frost Blast.

This is one of the little perks that only someone that did KT vanilla on retail can spot.

**Comment by ender-feenix** [comment]
I actually researched this pretty thoroughly. There is no evidence of any mechanic making it impossible, however it was significantly less likely on retail due to the more randomized timers.  Our new Kel'Thuzad script which is already under testing will implement this.  It should be essentially the same thing.
