### ISSUE TITLE
Al Al'kir Incorrect Gotthik Mobs Hp Value

### ISSUE THREAD

**Issue by piratic0** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5257]
The HP values tuning on the Gothik fight for Al'Akir diverge significantly from what they are on Warsong. It was readily apparent on Gothik himself, who had 5million more life than he should have before being hotfixed shortly after the release of Naxx, however after months of attempts in this encounter, we've come to realize that the trash HP values before he hits the floor is significantly off as well.

Al'Akir / Warsong

Unrelenting Trainee 25.2k / 8.5k
Unrelenting DeathKnight 35.7k / 32.8k
Unrelenting Rider 42.7k / 37.8k

Spectral Trainee	17.5k / 9.0k
Spectral Horse 35.5k / 39.4k
Spectral DeathKnight 75.3k / 27.21k
Spectral Rider ? / 20.9k

Al'Akir values, screenshots:
http://s1118.photobucket.com/user/SAWC/media/ss/gotthik8.jpg.html?sort=3&o=0

Warsong values, videos (Warsong server, Work in Progress guild):
https://www.youtube.com/watch?v=CYqSIYvouzs
https://www.youtube.com/watch?v=p6ZBciZbl6Y

The numbers may not be 100% accurate, but:

There are ~13 waves of Unrelenting Trainees, each of which spawn 3 trainees on the living side. The HP differential is 16,700 per trainee; ~13*3*16,700hp is an additional ~ 651,000 damage that the raid needs to put out on trainees alone. Spectral Trainee's also appear to have a higher HP pool than they should, and two spawn on UD side per Unrelenting Trainee killed.
(13*3*2*8,500hp = ~ 663,000 more damage the raid needs to put out on Spectrail Trainees)

**Comment by Goanno** [comment]
As the HP values of all the other Naxxramas bosses is set at 90% of Warsong HP values due to differences in average gearlevel I believe the following healthpools would be reasonable for Al'Akir:

Unrelenting Trainee:  7650
Unrelenting DeathKnight:  29520
Unrelenting Rider:  34000

Spectral Trainee:  8100
Spectral Horse: 35460
Spectral DeathKnight:  24490
Spectral Rider: 18810

However, even the current Warsong values as given above should be realistic.

**Comment by Forcy** [comment]
Will be fixed on live before next ID reset!

**Comment by Forcy** [comment]
A fix for this has been applied on Al'akir and will take effect upon next server restart.
